-- ============================================================================
-- Puregram Control — schema additions for the web app (applied on every boot).
--
-- These tables back the email/password Puregram Control web app:
-- control users, the manager↔managed graph, and the consent (link-request)
-- flow. The chat whitelist itself stays in the device tables (telegram_*); a
-- managed user's tg_user_id fans out to customers.tg_user_id → its devices.
--
-- Every statement is idempotent (CREATE ... IF NOT EXISTS). Timestamps are the
-- same zero-padded ISO-8601 UTC TEXT used elsewhere, so lexicographic compare
-- is chronological. Argon2id password hashes (auth.hash_password).
-- ============================================================================

-- ── Control users (email/password accounts for the web app) ────────────────
CREATE TABLE IF NOT EXISTS control_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         TEXT UNIQUE NOT NULL,            -- normalized lower-case
    password_hash TEXT NOT NULL,                   -- Argon2id
    display_name  TEXT,
    lang          TEXT NOT NULL DEFAULT 'ar' CHECK (lang IN ('ar','en')),
    tg_user_id    BIGINT,                          -- Telegram account this user owns (managed side)
    tg_verified   INTEGER NOT NULL DEFAULT 0,
    share_code    TEXT UNIQUE,                     -- random token, for linking by code
    created_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at    TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    last_seen_at  TEXT
);
-- One Telegram account maps to at most one control user.
CREATE UNIQUE INDEX IF NOT EXISTS uq_control_users_tg
    ON control_users(tg_user_id) WHERE tg_user_id IS NOT NULL;

-- ── The manage graph between control users (manager controls managed) ──────
CREATE TABLE IF NOT EXISTS control_links (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_user_id  BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    managed_user_id  BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    status           TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','revoked')),
    created_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    CHECK (manager_user_id <> managed_user_id),
    UNIQUE (manager_user_id, managed_user_id)
);
CREATE INDEX IF NOT EXISTS idx_control_links_mgr ON control_links(manager_user_id, status);
CREATE INDEX IF NOT EXISTS idx_control_links_mgd ON control_links(managed_user_id, status);

-- ── Consent: a manager requests to manage a target; the target approves ────
CREATE TABLE IF NOT EXISTS control_link_requests (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    target_user_id    BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    status            TEXT NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','approved','declined','cancelled')),
    created_at        TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at        TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    CHECK (requester_user_id <> target_user_id)
);
-- At most one pending request per (requester, target).
CREATE UNIQUE INDEX IF NOT EXISTS uq_link_req_pending
    ON control_link_requests(requester_user_id, target_user_id) WHERE status = 'pending';

-- ── Device-initiated supervisor pairing (Settings ▸ Help ▸ Link a supervisor) ─
-- A managed (child) account is auto-provisioned from a device's reported
-- tg_user_id with NO email/password: it is actable only via the device bearer
-- token + its supervisors, never web-loginable. So email/password_hash must be
-- nullable. Both statements are no-ops when the column is already nullable, so
-- they are safe to re-run on every boot alongside the CREATEs above.
ALTER TABLE control_users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE control_users ALTER COLUMN password_hash DROP NOT NULL;

-- The managed phone mints a short-lived, single-use code; a supervisor redeems
-- it from the web app (marks it 'claimed'); the phone then CONFIRMS the named
-- supervisor before the control_link goes active — consent stays on the handset.
-- Only the keyed HMAC of the code is stored (never the code itself), so a DB read
-- alone cannot recover a live code. `pair_id` is an opaque, non-secret handle the
-- device polls with, so the secret code never lands in a query string / log.
CREATE TABLE IF NOT EXISTS control_pairings (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pair_id            TEXT UNIQUE NOT NULL,          -- opaque device-poll handle (uuid)
    code_hash          TEXT UNIQUE NOT NULL,          -- HMAC-SHA256(normalized code, jwt_secret)
    device_id          TEXT NOT NULL,                 -- initiating device
    tg_user_id         BIGINT NOT NULL,               -- snapshot at mint time
    supervisor_user_id BIGINT REFERENCES control_users(id) ON DELETE SET NULL,
    status             TEXT NOT NULL DEFAULT 'pending'
                       CHECK (status IN ('pending','claimed','confirmed','rejected','cancelled','expired')),
    created_at         TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    expires_at         TEXT NOT NULL,
    claimed_at         TEXT,
    confirmed_at       TEXT
);
CREATE INDEX IF NOT EXISTS idx_control_pairings_device ON control_pairings(device_id, status);

-- Managed-side unlink requests: per product policy the managed user CANNOT
-- unilaterally unlink; they file a request the supervisor is notified of and
-- approves (which revokes the control_link).
CREATE TABLE IF NOT EXISTS control_unlink_requests (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_user_id  BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    managed_user_id  BIGINT NOT NULL REFERENCES control_users(id) ON DELETE CASCADE,
    status           TEXT NOT NULL DEFAULT 'pending'
                     CHECK (status IN ('pending','approved','denied','cancelled')),
    created_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at       TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
-- At most one pending unlink request per (manager, managed).
CREATE UNIQUE INDEX IF NOT EXISTS uq_unlink_req_pending
    ON control_unlink_requests(manager_user_id, managed_user_id) WHERE status = 'pending';

-- ── PER-ACCOUNT whitelist (2026-07-05) ─────────────────────────────────────
-- Filtering is now keyed by the Telegram ACCOUNT (tg_user_id), not the device.
-- Each account is deny-by-default: a newly added account has NO approved chats
-- until a supervisor allows them, so a managed user cannot escape supervision by
-- adding a fresh account. A device may host several accounts, each filtered
-- independently by its own approved set.

-- Which Telegram accounts are logged in on a device (the multi-account roster).
CREATE TABLE IF NOT EXISTS customer_accounts (
    customer_id TEXT   NOT NULL,
    tg_user_id  BIGINT NOT NULL,
    created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    PRIMARY KEY (customer_id, tg_user_id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_customer_accounts_tg ON customer_accounts(tg_user_id);

-- ── Panel-initiated linking (2026-07-26) ───────────────────────────────────
-- Supervision moved OUT of the messenger apps into the web panel: no pairing
-- code is ever shown on a handset. Instead the supervisor types the managed
-- account's @username / numeric id in the panel, and the handset receives a
-- NOTIFICATION carrying a short verification code plus approve/decline actions.

-- The reported Telegram identity of each account, so the panel can find it.
ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS username     TEXT;
ALTER TABLE customer_accounts ADD COLUMN IF NOT EXISTS display_name TEXT;
CREATE INDEX IF NOT EXISTS idx_customer_accounts_username
    ON customer_accounts (LOWER(username));

-- `code` is a VERIFICATION code, not a credential: approving a request requires
-- the managed handset's own bearer token, so knowing the code grants nothing.
-- It exists only so the managed user can see that the request on screen is the
-- one their supervisor is looking at. Hence plaintext (both sides display it).
ALTER TABLE control_link_requests ADD COLUMN IF NOT EXISTS code       TEXT;
ALTER TABLE control_link_requests ADD COLUMN IF NOT EXISTS expires_at TEXT;
ALTER TABLE control_link_requests ADD COLUMN IF NOT EXISTS notified_at TEXT;
CREATE INDEX IF NOT EXISTS idx_link_requests_target
    ON control_link_requests (target_user_id, status);

-- ── Known chats belong to an ACCOUNT, not a device (2026-07-27) ────────────
-- One handset may host several Telegram accounts, and one account may run on
-- several handsets. Keying reported chats by customer alone merged two accounts'
-- chat lists on a shared device, and lost an account's chats when the device
-- switched accounts. Keying by (customer, tg_user_id) makes each account's list
-- its own, and the union across an account's devices is simply
-- `WHERE tg_user_id = …` — which is also the key the whitelist is enforced by.
ALTER TABLE telegram_known_chats ADD COLUMN IF NOT EXISTS tg_user_id BIGINT;

-- Backfill: attribute existing rows to the account the device last reported.
UPDATE telegram_known_chats k
   SET tg_user_id = c.tg_user_id
  FROM customers c
 WHERE c.id = k.customer_id
   AND k.tg_user_id IS NULL
   AND c.tg_user_id IS NOT NULL;
-- Rows we cannot attribute (device never reported an account) get 0, which no
-- real Telegram id uses, so they simply never match an account query.
UPDATE telegram_known_chats SET tg_user_id = 0 WHERE tg_user_id IS NULL;
ALTER TABLE telegram_known_chats ALTER COLUMN tg_user_id SET DEFAULT 0;
ALTER TABLE telegram_known_chats ALTER COLUMN tg_user_id SET NOT NULL;

-- Widen the primary key to include the account. Guarded on the old 2-column key
-- so re-running on every boot is a no-op.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM pg_constraint
         WHERE conname = 'telegram_known_chats_pkey'
           AND array_length(conkey, 1) = 2
    ) THEN
        ALTER TABLE telegram_known_chats DROP CONSTRAINT telegram_known_chats_pkey;
        ALTER TABLE telegram_known_chats
            ADD CONSTRAINT telegram_known_chats_pkey
            PRIMARY KEY (customer_id, tg_user_id, chat_id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_tg_known_account
    ON telegram_known_chats (tg_user_id, last_seen_at);

-- The approved chats for an ACCOUNT (allowed=0 = explicitly revoked/denied).
CREATE TABLE IF NOT EXISTS telegram_account_whitelist (
    tg_user_id BIGINT  NOT NULL,
    chat_id    BIGINT  NOT NULL,
    kind       TEXT    NOT NULL CHECK (kind IN ('channel','group','private','bot')),
    label      TEXT,
    allowed    INTEGER NOT NULL DEFAULT 1,
    granted_by TEXT,
    created_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    PRIMARY KEY (tg_user_id, chat_id)
);

-- Per-account whitelist version for cheap client polling.
CREATE TABLE IF NOT EXISTS telegram_account_whitelist_meta (
    tg_user_id BIGINT PRIMARY KEY,
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- One-time, marker-guarded migration of the legacy per-DEVICE approvals into the
-- new per-ACCOUNT tables (so existing supervised accounts keep their allowed set).
CREATE TABLE IF NOT EXISTS schema_migrations (
    name       TEXT PRIMARY KEY,
    applied_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE name = 'account_whitelist_v1') THEN
        INSERT INTO telegram_account_whitelist
            (tg_user_id, chat_id, kind, label, allowed, granted_by, created_at, updated_at)
        SELECT c.tg_user_id, w.chat_id, MAX(w.kind), MAX(w.label),
               MAX(w.allowed), MAX(w.granted_by), MIN(w.created_at), MAX(w.updated_at)
          FROM telegram_whitelist w
          JOIN customers c ON c.id = w.customer_id
         WHERE c.tg_user_id IS NOT NULL
         GROUP BY c.tg_user_id, w.chat_id
        ON CONFLICT (tg_user_id, chat_id) DO NOTHING;

        INSERT INTO telegram_account_whitelist_meta (tg_user_id, version, updated_at)
        SELECT c.tg_user_id, MAX(m.version), MAX(m.updated_at)
          FROM telegram_whitelist_meta m
          JOIN customers c ON c.id = m.customer_id
         WHERE c.tg_user_id IS NOT NULL
         GROUP BY c.tg_user_id
        ON CONFLICT (tg_user_id) DO NOTHING;

        INSERT INTO customer_accounts (customer_id, tg_user_id)
        SELECT id, tg_user_id FROM customers WHERE tg_user_id IS NOT NULL
        ON CONFLICT (customer_id, tg_user_id) DO NOTHING;

        INSERT INTO schema_migrations (name) VALUES ('account_whitelist_v1');
    END IF;
END $$;
