-- ============================================================================
-- Puregram control plane — PostgreSQL schema (applied on every startup).
--
-- Every statement is idempotent (CREATE ... IF NOT EXISTS / ALTER ... IF NOT
-- EXISTS), so running this script repeatedly is safe. Timestamps are stored as
-- zero-padded ISO-8601 UTC TEXT so lexicographic comparison is chronological.
-- ============================================================================

-- ── Devices (one row per managed device) ──────────────────────────────────
-- device_id = Settings.Secure.ANDROID_ID (no permission, stable across reboots).
-- The historic name "customers" is kept so route code reads naturally; here a
-- row is simply a device the Puregram client checked in from.
CREATE TABLE IF NOT EXISTS customers (
    id              TEXT PRIMARY KEY,               -- uuid
    device_id       TEXT UNIQUE NOT NULL,
    brand           TEXT,
    manufacturer    TEXT,
    model           TEXT,
    android_version TEXT,
    sdk_int         INTEGER,
    created_at      TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at      TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    last_seen_at    TEXT
);
CREATE INDEX IF NOT EXISTS idx_customers_device_id ON customers(device_id);
-- Telegram account this device is logged into (reported by the client after
-- login). Lets a manager control the whitelist by account, not just device.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS tg_user_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_customers_tg_user ON customers(tg_user_id);

-- ── Device bearer tokens (no DB/service key ships in the client) ───────────
CREATE TABLE IF NOT EXISTS device_tokens (
    device_id    TEXT PRIMARY KEY,
    token        TEXT UNIQUE NOT NULL,
    created_at   TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    last_used_at TEXT
);

-- ── Admin accounts — REMOVED ───────────────────────────────────────────────
-- ADR-002 has no operator: every user governs their own lists, so the service
-- has no privileged role to sign in as. The login, session and admin-management
-- endpoints are gone along with the table.
--
-- The `admins` table is deliberately NOT dropped here. A DROP in a file that
-- runs on every deploy would destroy the old rows the first time it ran, and
-- they cost nothing sitting unread. Drop it by hand once you are sure:
--   DROP TABLE IF EXISTS admins;

-- ── Append-only activity log ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id TEXT,
    actor       TEXT NOT NULL,                       -- telegram|admin|system
    action      TEXT NOT NULL,
    target      TEXT,
    payload     TEXT NOT NULL DEFAULT '{}',
    ip_address  TEXT,
    created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_customer ON audit_log(customer_id);

-- (Standalone licenses / subscriptions were REMOVED — Puregram is free. Access
-- is governed entirely by the per-device Telegram whitelist below. The legacy
-- `app_licenses` table is no longer created or used; drop it on existing DBs
-- with: DROP TABLE IF EXISTS app_licenses;)

-- ── Telegram: per-device chat whitelist (the Puregram client) ──────────────
CREATE TABLE IF NOT EXISTS telegram_whitelist (
    customer_id TEXT    NOT NULL,
    chat_id     BIGINT  NOT NULL,
    kind        TEXT    NOT NULL
                CHECK (kind IN ('channel','group','private','bot')),
    label       TEXT,
    allowed     INTEGER NOT NULL DEFAULT 1,           -- 0 = explicitly revoked
    granted_by  TEXT,                                 -- admin email
    created_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    PRIMARY KEY (customer_id, chat_id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- ── Telegram: chats the device's account can actually see ──────────────────
CREATE TABLE IF NOT EXISTS telegram_known_chats (
    customer_id   TEXT    NOT NULL,
    chat_id       BIGINT  NOT NULL,
    kind          TEXT    NOT NULL
                  CHECK (kind IN ('channel','group','private','bot')),
    title         TEXT,
    username      TEXT,
    first_seen_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    last_seen_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    PRIMARY KEY (customer_id, chat_id),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tg_known_customer
    ON telegram_known_chats(customer_id, last_seen_at);

-- ── Telegram: whitelist version per device (cheap client polling) ──────────
CREATE TABLE IF NOT EXISTS telegram_whitelist_meta (
    customer_id TEXT PRIMARY KEY,
    version     INTEGER NOT NULL DEFAULT 0,
    updated_at  TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
);

-- ── Per-account chat rules (ADR-002, 2026-09-05) ───────────────────────────
-- No curated global list. Each Telegram account governs its own client, and the
-- rules are keyed by account so they follow it across devices.
--   * people (non-bot users) always open;
--   * channels, bots and groups are closed until the account allows them;
--   * `allow` is reversible, `block` is PERMANENT — the ratchet is enforced in
--     the upsert in routes/rules.py, not just in the clients.
CREATE TABLE IF NOT EXISTS account_rules (
    tg_user_id BIGINT NOT NULL,
    chat_id    BIGINT NOT NULL,     -- dialog-id encoding: user/bot +id, group/channel -id
    kind       TEXT   NOT NULL CHECK (kind IN ('channel','bot','group','user')),
    username   TEXT,                -- for display only; matching is by chat_id
    title      TEXT,                -- chat title at the time the rule was set
    rule       TEXT   NOT NULL CHECK (rule IN ('allow','block')),
    created_at TEXT   NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    updated_at TEXT   NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    PRIMARY KEY (tg_user_id, chat_id)
);
CREATE INDEX IF NOT EXISTS idx_account_rules_rule ON account_rules(tg_user_id, rule);

-- Per-account version so a client can poll for changes for ~0 bytes.
CREATE TABLE IF NOT EXISTS account_rules_meta (
    tg_user_id BIGINT PRIMARY KEY,
    version    INTEGER NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT to_char(now() AT TIME ZONE 'utc','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
);

-- The ADR-001 global list is gone. Drop it wherever it still exists.
DROP TABLE IF EXISTS policy_entries;
DROP TABLE IF EXISTS policy_settings;

-- Erasure requests. Google Play requires a data-deletion path; it does not
-- require it to be instant. Deleting the rules also clears the permanent blocks,
-- so the request is recorded here and carried out only after the waiting period
-- (routes/rules.run_due_erasures). The user may cancel until then.
CREATE TABLE IF NOT EXISTS account_erasures (
    tg_user_id   BIGINT PRIMARY KEY,
    status       TEXT NOT NULL DEFAULT 'pending'
                 CHECK (status IN ('pending','cancelled','done')),
    requested_at TEXT NOT NULL,
    effective_at TEXT NOT NULL,
    updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_account_erasures_due
    ON account_erasures(status, effective_at);

-- ── Which devices may act for an account (ADR-002 §8) ──────────────────────
-- The device bearer token proves WHICH DEVICE is calling, but not that the
-- device is signed into the Telegram account it claims — Telegram gives a
-- third-party client nothing our server could verify. So: the first device to
-- claim an account owns it (trust on first use); any later device lands in
-- `pending` and an already-active device approves it. A pending claim also
-- auto-approves after a waiting period, so someone who reinstalls on their only
-- handset is not locked out for ever — and an attacker's claim is visible on the
-- real device for that whole window, waiting to be denied.
CREATE TABLE IF NOT EXISTS account_devices (
    tg_user_id      BIGINT NOT NULL,
    device_id       TEXT   NOT NULL,
    status          TEXT   NOT NULL DEFAULT 'pending'
                    CHECK (status IN ('active','pending','denied')),
    model           TEXT,
    created_at      TEXT   NOT NULL,
    updated_at      TEXT   NOT NULL,
    auto_approve_at TEXT,
    PRIMARY KEY (tg_user_id, device_id)
);
CREATE INDEX IF NOT EXISTS idx_account_devices_status
    ON account_devices(tg_user_id, status);
